# Kibana is served by a back end server. This setting specifies the port to use.
server.port: 5601
# Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: "0"
# The URL of the Elasticsearch instance to use for all your queries.
elasticsearch.url: http://search:9200
# X-Pack extension configuration.
xpack.monitoring.ui.container.elasticsearch.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.reporting.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false
