<?php
/**
 * Created by PhpStorm.
 * User: ikesimmons
 * Date: 25.06.18
 * Time: 16:21
 */

namespace Pyz\Shared\Mail;

use Spryker\Shared\Mail\MailConstants as SprykerMailConstants;

interface MailConstants extends SprykerMailConstants
{
    public const MAIL_ASSETS_BASE_URL = 'MAIL_ASSETS_BASE_URL';
    public const MAIL_CUSTOMER_SURVEY_URL = 'MAIL_CUSTOMER_SURVEY_URL';
    public const MAIL_CUSTOMER_SURVEY_HAPPINESS = 'MAIL_CUSTOMER_SURVEY_HAPPINESS';
    public const MAIL_CUSTOMER_PAYMENT_FEEDBACK_URL = 'MAIL_CUSTOMER_PAYMENT_FEEDBACK_URL';

    public const MAIL_DURST_COMPANY_NAME = 'MAIL_DURST_COMPANY_NAME';
    public const MAIL_DURST_COMPANY_STREET = 'MAIL_DURST_COMPANY_STREET';
    public const MAIL_DURST_COMPANY_CITY = 'MAIL_DURST_COMPANY_CITY';
    public const MAIL_DURST_COMPANY_WEB = 'MAIL_DURST_COMPANY_WEB';
    public const MAIL_DURST_COMPANY_EMAIL = 'MAIL_DURST_COMPANY_EMAIL';
    public const MAIL_DURST_COMPANY_VAT_ID = 'MAIL_DURST_COMPANY_VAT_ID';
    public const MAIL_DURST_COMPANY_BIO = 'MAIL_DURST_COMPANY_BIO';
    public const MAIL_DURST_COMPANY_JURISDICTION = 'MAIL_DURST_COMPANY_JURISDICTION';
    public const MAIL_DURST_COMPANY_MANAGEMENT = 'MAIL_DURST_COMPANY_MANAGEMENT';

    public const MAIL_FOOTER_BANNER_IMG = 'MAIL_FOOTER_BANNER_IMG';
    public const MAIL_FOOTER_BANNER_LINK = 'MAIL_FOOTER_BANNER_LINK';
    public const MAIL_FOOTER_BANNER_ALT = 'MAIL_FOOTER_BANNER_ALT';
    public const MAIL_FOOTER_BANNER_CTA = 'MAIL_FOOTER_BANNER_CTA';

    public const MAIL_FRIDGE_URL = 'MAIL_FRIDGE_URL';
    public const MAIL_MERCHANT_CENTER_BASE_URL = 'MAIL_MERCHANT_CENTER_BASE_URL';

    public const MAIL_RECIPIENT_DEVELOPER = 'MAIL_RECIPIENT_DEVELOPER';
    public const MAIL_RECIPIENT_SERVICE = 'MAIL_RECIPIENT_SERVICE';

    public const MAIL_CANCEL_ORDER_BASE_URL = 'MAIL_CANCEL_ORDER_BASE_URL';

    public const MAIL_SMTP_HOST = 'MAIL_SMTP_HOST';
    public const MAIL_SMTP_PORT = 'MAIL_SMTP_PORT';
}
