groups:
    EU:
        region: EU
        applications:
            merchant_portal_eu:
                application: merchant-portal
                endpoints:
                    mp.de.spryker.local:
                        entry-point: MerchantPortal
                        store: DE
                        primal: true
                        services:
                            session:
                                namespace: 7
                    mp.at.spryker.local:
                        entry-point: MerchantPortal
                        store: AT
                        services:
                            session:
                                namespace: 8
            yves_eu:
                application: yves
                endpoints:
                    date-time-configurator-example.spryker.local:
                        entry-point: Configurator
                    yves.de.spryker.local:
                        store: DE
                        services:
                            session:
                                namespace: 1
                    yves.at.spryker.local:
                        store: AT
                        services:
                            session:
                                namespace: 2
            glue_eu:
                application: glue
                endpoints:
                    glue.de.spryker.local:
                        store: DE
                    glue.at.spryker.local:
                        store: AT
            backoffice_eu:
                application: backoffice
                endpoints:
                    backoffice.de.spryker.local:
                        store: DE
                        primal: true
                        services:
                            session:
                                namespace: 3
                    backoffice.at.spryker.local:
                        store: AT
                        services:
                            session:
                                namespace: 4
            backend_gateway_eu:
                application: backend-gateway
                endpoints:
                    backend-gateway.de.spryker.local:
                        store: DE
                        primal: true
                    backend-gateway.at.spryker.local:
                        store: AT
                        primal: true
            backend_api_eu:
                application: zed
                endpoints:
                    backend-api.de.spryker.local:
                        store: DE
                        entry-point: BackendApi
                    backend-api.at.spryker.local:
                        store: AT
                        entry-point: BackendApi

    US:
        region: US
        applications:
            merchant_portal_us:
                application: merchant-portal
                endpoints:
                    mp.us.spryker.local:
                        entry-point: MerchantPortal
                        store: US
                        services:
                            session:
                                namespace: 9
            yves_us:
                application: yves
                endpoints:
                    yves.us.spryker.local:
                        store: US
                        services:
                            session:
                                namespace: 5
            glue_us:
                application: glue
                endpoints:
                    glue.us.spryker.local:
                        store: US
            backoffice_us:
                application: backoffice
                endpoints:
                    zed.us.spryker.local:
                        store: US
                        services:
                            session:
                                namespace: 6
            backend_gateway_us:
                application: backend-gateway
                endpoints:
                    backend-gateway.us.spryker.local:
                        store: US
            backend_api_us:
                application: zed
                endpoints:
                    backend-api.us.spryker.local:
                        store: US
